### PR TITLE
Recompute attributes containing user environment values

### PR DESCRIPTION
**Pull request by gastaldi**
Recompute attributes containing user environment values

### CODE REVIEW

**Comment by gastaldi** [comment]
@PierreBtz can you give it a try with this PR? I think it should solve your problem

**Comment by PierreBtz** [comment]
@gastaldi thanks for the very fast fix!

I confirm this PR fixes both my repro and also my actual project!

**Comment by gastaldi** [comment]
@PierreBtz  thank you for the issue and reproducer. I released 3.0.4 now. Enjoy!

**Comment by gastaldi** [comment]
@all-contributors add @PierreBtz for bug

**Pull request merged**
