### PR TITLE
Introduce a Gitea DevService

### LINKED ISSUE #140: Provide a dev service for git
A bit portion if the jgit functionality does require access to a remote server.
Using own accounts on github, gitlab or similar is dangerous in so many different ways:
- accidents can happen
- credentials can leak

It would be so much better / easier for users to have a dev service they can use.

This can also make sense for other extensions using `quarkus-jgit` and their own dev services do require access to a git server (e.g. quarkus-backstage or quarkus-argocd). See:
- https://github.com/quarkiverse/quarkus-backstage/issues/15

### Alterntives (?)
An alternative could be setting up bare repositories. This is something that could work for unit testing etc.
I am not really sure however, if this would be well respected for integration with other extensions, as they may not accept paths etc.

### Implementation ideas
Maybe we could use something like:
- gitea
- gogs
- gitbucket

### PR DESCRIPTION
**Pull request by gastaldi**
- Fixes #140

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by iocanel** [comment]
@gastaldi you rock!

**Comment by gastaldi** [comment]
One thing I haven't figured out yet is how to configure a user and create a test repository when starting up the service, but we can iterate on that later

**Comment by gastaldi** [comment]
Support for Admin user and password added! Now to create a repository

**Comment by gastaldi** [comment]
I'll defer the repository creation to another PR.

**Comment by iocanel** [comment]
@gastaldi came in to say that it works fine, but we should probably add a mechanism for creating users etc, but you beat me to it!

**Pull request merged**
